# Generated by Django 4.2.3 on 2023-07-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ConfPass',
            new_name='Confirm',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Fname',
            new_name='First',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Lname',
            new_name='Last',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Pass',
            new_name='Password',
        ),
    ]
